version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
